build-doc:
  tags:
    - ub-linux-64
  script:
    - cd ..
    - echo 'Start job as' `whoami` ' in folder ' `pwd`
    - if [ -d ldoc ] && [ -d ldoc/.git ]; then cd ldoc; git reset --hard master; git checkout master; git pull; else git clone ssh://git@git-pub.intecracy.com:9922/unitybase/ldoc.git; cd ldoc; git checkout master; fi
    - cd ../ubjs
    - NODE_ENV=production npm i
    - npm ddp
    - cp -rf ./node_modules/ub-jsdoc/templateHelper.js-patched ./node_modules/jsdoc/lib/jsdoc/util/templateHelper.js
    - wget -nv -O samples-master.zip https://git-pub.intecracy.com/unitybase/samples/-/archive/master/samples-master.zip
    - unzip -o samples-master.zip "samples-master/courses/tutorial-v5/*" -d getting-started
    - npm run build:doc
    - rsync -avz -e "ssh -p 2222" docs/* gitlab-builder@registry.unitybase.info:/home/ub-service/website/unitybase-info/inetPub/api
  when: manual
  only:
    - master
