build-doc:
  tags:
    - ub-linux-64
  script:
#    - cd ..
    - echo 'Start job as' `whoami` ' in folder ' `pwd`
#    - if [ -d ldoc ] && [ -d ldoc/.git ]; then cd ldoc; git reset --hard master; git checkout master; git pull; else git clone ssh://git@git-pub.intecracy.com:9922/unitybase/ldoc.git; cd ldoc; git checkout master; fi
#    - cd ../ubjs
    - NODE_ENV=production npm i
    - npm ddp
    - cp -rf ./node_modules/ub-jsdoc/templateHelper.js-patched ./node_modules/jsdoc/lib/jsdoc/util/templateHelper.js
    - wget -nv -O samples-master.zip https://git-pub.intecracy.com/unitybase/samples/-/archive/master/samples-master.zip
    - unzip -o samples-master.zip "samples-master/courses/tutorial-v5/*" -d getting-started
    - npm run build:doc
#    - npx lerna bootstrap --no-ci --ignore-scripts
#    - cd apps/docs-adminui
#    - mkdir -p ./inetpub
#    - npm run build:prod
#    - cd inetpub
#    - tar --exclude-vcs --exclude-backups -zc --dereference -f ../uidoc.tar.gz .
#    - cd ..
#    - scp ./uidoc.tar.gz         gitlab-builder@10.23.4.53:/home/ub-service/website/unitybase-info/inetPub
#    - cd ../..
    - rsync -avz -e "ssh" docs/* gitlab-builder@10.23.4.53:/home/ub-service/website/unitybase-info/inetPub/api
  when: manual
  only:
    - master
