build-doc:
  tags:
    - ub-linux-64
  script:
    - npm i
    - cp -rf ./node_modules/ub-jsdoc/templateHelper.js-patched ./node_modules/jsdoc/lib/jsdoc/util/templateHelper.js
    - npm run build:doc
    - rsync -avz -e "ssh -p 2222" docs/{server-v5,ubpub-v5} gitlab-builder@registry-tst.unitybase.info:/home/ub-service/website/unitybase-info/inetPub/api
  when: manual
  only:
    - master