<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    width="100%"
    height="100%"
    viewBox="0 0 100 100"
    fill="none"
    preserveAspectRatio="none"
    class="u-file__dropzone-icon"
  >
    <defs>
      <pattern
        id="newpattern"
        x="0"
        y="0"
        width="15"
        height="100%"
        patternUnits="userSpaceOnUse"
        patternTransform=""
      >
        <g fill="rgba(255,255,255, 0.5)">
          <rect
            x="0"
            y="0"
            width="7"
            height="100%"
          />
        </g>
        <animateTransform
          attributeName="patternTransform"
          type="translate"
          dur="40s"
          from="0"
          to="1000"
          begin="0s"
          repeatCount="indefinite"
        />
      </pattern>
    </defs>
    <rect
      x="0"
      y="0"
      width="110%"
      height="100%"
      style="fill: url(#newpattern); transform: skewX(-4deg)"
    />
  </svg>
</template>
