/* global Ext UB */
/**
 * UnityBase Tajik translation.
 */
UB.i18nExtend({
  emptyBarcodeSettings: 'Пеш аз истифодаи штрих-код, шумо бояд онро танзим кунед.',
  setScannerSettings: 'Пеш аз истифодаи сканер бори аввал шумо бояд онро танзим кунед. Шумо метавонед <a href="/" onclick="{0} return false;">дар ин ҷой танзим кунед</a>.',
  showResultConfig: 'Намоиши танзимот',
  numberOfSignificantDigits: 'Миқдори аломатҳои муҳим имконпазир аст',
  yearShort: 'р.',
  PastTooLargeText: 'Шумо миқдори калонеро ворид мекунед. Ин амалиёт метавонад вақти зиёдро талаб кунад. Мехоҳед давом диҳед?',
  gridOptimizeWidth: 'Автоподбор ширины',
  showDeveloperDetail: 'Детали для разработчика',
  pleaseInputValueToThisField: 'Заполните значение',
  Audit: 'Аудит',
  gridEmptySelection: 'Ягон сабти бақайдгирӣ интихоб нашудааст.',
  gridItemLink: 'Ссылка на пункт',
  gridCategoryCaption: 'Гурӯҳ',
  gridFavoritesCaption: 'Избранное',
  info: 'Маълумот',
  error: 'Ошибка',
  detail: 'Муфассал',
  uk: 'Украинӣ',
  en: 'Англисӣ',
  ru: 'Русӣ',
  az: 'Озарбойҷонӣ',
  tg: 'Тоҷикӣ',
  id: 'Индонезӣ',
  ka: 'Гурҷӣ',
  ky: 'Қирғизӣ',
  formConstructor: 'Конструктор форм',
  isAutoGeneratedForm: 'Ин шакл ба таври худкор тавлид мешавад.',
  formNotFound: 'Форма ёфт нашуд',
  requiredField: 'Ин майдон ҳатмист барои пур кардан',
  General: 'Умумӣ',
  missingDescriptionAttribute: "Амволи  'descriptionAttribute': '{0}'объект ягон хусусияти '{1}' ғайримуқаррариро нишон медиҳад",
  userSettings: 'Танзимот',
  Desktop: 'Рабочий стол',
  unknownCommand: 'Дастурамали номаълум',
  unknownCommandType: 'Намуди дастурамали номаълум',
  unknownEntityInCommand: 'Неверно описана команда "{0}" для сущности "{1}". Атрибут entity указан неверно.',
  Entity: 'Сущность',
  Copy: 'Нусхабардоштан',
  Edit: 'Вироштан',
  Delete: 'Удалить',
  vseDeystviya: 'Ҳама амалҳо',
  saveAndClose: 'Захира кардан ва пӯшиданд',
  storedData: 'Маълумоти захирашуда',
  resetGUIToDefault: 'Танзимоти интерфейс "бо нобаенӣ"',
  clearLocalStore: 'Очистить локальное хранилище',
  novajaVersija: 'Нусхаи нав',
  aktualnoS: 'Актуально с',
  refresh: 'Обновить',
  obrazDocumenta: 'Тасвири ҳуҷҷат',
  link: 'Ссылка',
  External: 'Внешняя',
  ChangesHistory: 'История изменений',
  Details: 'Детали',
  Filter: 'Фильтр',
  s: 'аз',
  po: 'то',
  pluginNeUstanovlen: 'Плагин насб нашудааст',
  pluginNedostupen: 'Плагин дастнорас аст',
  nastroykiSkanera: 'Танзимоти сканер',
  skanirovat: 'Сканировать',
  skanirovanieAtributa: 'Сканирование атрибута',
  izFayla: 'Аз файл',
  shtrikhKod: 'Штрих-код',
  dokument: 'Ҳуҷҷат',
  fayl: 'Файл',
  pleaseWait: 'Лутфан мунтазир шавед...',
  loadingData: 'Боркунии маълумот...',
  zagruzka: 'Загрузка...',
  emptyContent: 'Содержимое не задано',
  vyHotiteUdalitSoderzhimoeDocumenta: 'Действительно удалить содержимое документа?',
  vyberiteFayl: 'Файлро интихоб кунед',
  dobavlenie: 'илова кардан',
  serverVremennoNedostupen: 'Сервер муваққатан дастнорас аст. Баъдтар бори дигар кӯшиш кунед ё бо мудири система тамос гиред.',
  deletionDialogConfirmCaption: 'Подтвердите удаление',
  deleteConfirmation: "Будет удалена запись из '{0}'. Шумо мутмаин ҳастед?",
  deleteConfirmationWithCaption: "Будет удалена запись {1} из '{0}'. Шумо мутмаин ҳастед?",
  deleteFormConfirmCaption: "Будет удалено '{0}'. Шумо мутмаин ҳастед?",
  rowEditing: 'Необходимо завершить редактирование данных',
  notValidForColumns: "Недопустимые значения в колонках {0}",
  vyUvereny: 'Шумо мутмаин ҳастед?',
  formDefinition: 'Тавсифи интерфейс',
  formModule: 'Тавсифи усулҳо',
  err_line: 'Строка',
  err_character: 'Столбец',
  err_description: 'Тавсифи хатоги',
  konsolOshibok: 'Консоль ошибок',
  accessRight: 'Иҷозатнома',
  vybrat: 'Интихоб кунед',
  redactirovat: 'Таҳрир кардан',
  addShortcut: 'Добавить ярлык',
  addFolder: 'Илова кардани папка',
  showPreview: 'Намоиш',
  exportXls: 'Содирот ба "Excel"',
  exportCsv: 'Содирот ба CSV',
  exportHtml: 'Содирот ба Html',
  'export': 'Содирот',
  readPKCanceled: 'Прервано пользователем',
  invalidPrivateKeyCertificate: 'Шаҳодатномаи(ҳои) нодурусти калиди хусусӣ  интихоб карда шуд. Барои калиди пас аз соли 2014 додашуда бояд ду шаҳодатнома дошта бошад.',
  currentPageNumber: 'Саҳифаи ҷорӣ',

  da: 'Ҳа',
  net: 'Не',
  showLetters: 'Показывать символы',
  tabsCountLimitExceeded: 'Открыто слишком много вкладок',
  unsavedData: 'Додаҳо захира нашудаанд',
  confirmFormClosing: 'Тағирот захира карда нашуд. Закрыть форму <b>с потерей введённых изменений</b>?',
  confirmSave: 'Мехоҳед тағиротро захира кунед?',
  original: 'Оригинал',
  ot: ' от ',
  do: ' до ',
  document: 'Документ',
  sign: 'Ворид шуданд',

  NMUBExtension: 'расширение "UBExtension"',
  NMFeatureScanner: 'Модуль поддержки сканирования',
  NMFeatureDSTU: 'Модуль шифрования ДСТУ',
  NMFeatureIIT: 'Модуль поддержки ЭЦП ИИТ',
  NMFeaturePDFSigner: 'Модуль подписания PDF',
  singOperationInProcess: 'Выполняется подписание другого документа. Повторите действие позже',

    // all messages below are formatted with 4 params [0=UB.i18n(featureInfo.UIName), 1=featureInfo.minVersion, 2=currentVersion, 3=installerDownloadPath]
  NMInstallExtensionChrome: '<p>Барои идома додани кор, шумо бояд як тавсеаи <b>"UBExtension"</b> браузер Google Chrome насб кунед.</p> ' +
        '<p>Нажмите на ссылку <a href="https://chrome.google.com/webstore/detail/ubextension/{3}" target="_blank">УСТАНОВИТЬ РАСШИРЕНИЕ</a> ' +
        ' для перехода в магазин Google</p>' +
        '<p> В окне магазина нажмите кнопку <img src="models/adminui-pub/ub-extension/ChromePlusFreeEn.png"/> (может быть <b>+РОЙГОН</b>)</p>' +
        '<p>Появится окно с подтверждением установки расширения - нажмите "Добавить" (Add).</p>' +
        '<p>Расширение будет установлено и кнопка <b>+FREE</b> изменит свой цвет на зелёный: <img src="models/adminui-pub/ub-extension/ChromeAddedEn.png"/> ' +
        '<p>После установки расширения <b>перезапустите браузер!</b></p>',
  NMInstallExtensionOpera: '<p>Для продолжения работы необходима установка расширения <b>"UBExtension"</b> для браузера Opera.</p> ' +
        '<p>Нажмите на ссылку <a href="models/adminui-pub/ub-extension/UBExtension.crx" target="_blank">УСТАНОВИТЬ РАСШИРЕНИЕ</a>.</p>' +
        '<p>Браузер тамдидро зеркашӣ мекунад ва ба шумо дар болои экран паём медиҳад. ' +
        'Дар панели огоҳӣ тугмачаи "Go" -ро (Гузаштан) пахш кунед- Opera саҳифаеро бо васеъкунакҳо насб мекунад. Он ҷо "UBExtension" -ро ёбед ва "Install" -ро (Насб) пахш намоед.</p> ' +
        '<p>Баъд аз ин, насб ба анҷом расидааст ва шумо бояд браузерро аз нав оғоз кунед.</p>',
  NMUpdateExtensionChrome: '<p>Для продолжения работы необходимо обновить <b>{0}</b> до версии <i>{2}</i>.</p> ' +
        '<p>Одатан браузери Google Chrome васеъкуниҳоро ба таври худкор нав мекунад. Кӯшиш кунед, бори дигар тугмачаи пӯшед / кушоед пахш намоед.' +
        ' Барои навсозиҳои дастӣ ба мағозаи Google бо ин пайванд <a href="https://chrome.google.com/webstore/detail/ubextension/{3}" target="_blank">гузаред</a> </p>',
  NMUpdateExtensionOpera: '<p>Барои идома додан, шумо бояд навсозӣ кунед <b>{0}</b> то версияи <i>{2}</i>.</p> ' +
        '<p>Одатан, браузери Opera васеъшавиро ба таври худкор навсозӣ мекунад. Кӯшиш кунед, бори дигар браузерро пӯшед / кушоед пахш намоед. ' +
        ' Для ручного обновления перейдите <a href="models/adminui-pub/ub-extension/UBExtension.crx" target="_blank">по этой ссылке</a> </p>',
  NMInstallFeature: '<p>Для использования этого функционала необходимо установить <b>{0}</b>.</p> ' +
        '<p>Нажмите на ссылку <a href="{3}" target="_blank">ЗАГРУЗИТЬ ИНСТАЛЛЯЦИЮ</a>. После завершения загрузки запустите инсталляцию и следуйте подсказкам.</p>' +
        '<p>После завершения инсталляции необходимо перезапустить браузер.</p>',
  NMUpdateFeature: '<p>Разработана новая версия <i>{1}</i> приложения <b>{0}</b>.</p> ' +
        '<p>Нажмите на ссылку <a href="{3}" target="_blank">ЗАГРУЗИТЬ ОБНОВЛЕНИЕ</a>. После завершения загрузки запустите обновление и следуйте подсказкам.</p>' +
        '<p>После завершения обновления необходимо перезапустить браузер.</p>',

  clear: 'Тоза кардан',
  signed: 'Подписано',
  term: 'Мӯҳлат',
  executed: 'Иҷро шуд',
  linkToDocItem: 'Пункт документа',
  filter: 'Фильтр',
  doubletAlertTitle: 'Дублеты документа',
  doubletAlertMsg: 'Найдены дубликаты документа: {0}. Шумо мехоҳед идома диҳед?',
  barcodeRegData: '{0} от {1}',
  barcodeSheets: 'лист.{0}',
  withoutNumber: 'Б/Н',
  withoutDate: 'Б/Д',
  partialDataLoaded: 'Маълумот қисман зеркашӣ карда шуд. Барои дидани ҳамаи вурудот дар ин ҷо пахш кунед',
  include: ' дар бар мегирад',
  tooManyItems: 'Вурудоти аз ҳад зиёд. Лутфан кӯшиш кунед, ки ҷустуҷӯятонро дақиқ кунед.',
  fetchAllRows: 'Загрузить все',
  rowCounts: 'Записей',
  doNotGetLock: 'Запись заблокирована пользователем {0} {1} сек. тому назад. Ҳама тағиротҳои воридшуда захира карда намешаванд. Попробуйте позднее.',
  persistLockInfo: 'Заблокировано {1}',
  softLockInfo: 'Заблокировано пользователем {0} в {1}',
  lockBtn: 'Заблокировать запись',
  unLockBtn: 'Разблокировать запись',
  tempSoftLockInfo: 'Ҳоло сабтро корбар таҳрир кардааст. {0}',
  recordLockedOtherUser: 'Запись заблокирована другим пользователем',
  recordLockedThisUser: 'Сабт аллакай баста шудааст',
  lockSuccessCreated: 'Сабт бо муваффақият баста шуд',
  recordLockedByTempLock: 'Ин мактубро корбари дигар таҳрир карда истодааст.',
  recordLockedThisUserByTempLock: 'Истифодабарандаи ҷорӣ сабтро таҳрир карда истодааст.',
  lockSuccessDeleted: 'Запись успешно разблокирована',
  recordNotLocked: 'Запись не заблокирована',
  tempLockExistForThisUser: 'Истифодабарандаи ҷорӣ вурудро дар дигар ҷадвал, дар равзанаи дигар ё дар компютери дигар таҳрир карда истодааст.',

  resolutionSignReason: 'Подписана резолюция',
  noStaffEmployeeShortFIO: 'Не назначено',
  made: 'Подготовлено',
  notSpecified: 'Не указано',
  forms: 'формы',
  Forms: 'Формы',
  searchOpportunities: 'Хусусиятҳои ҷустуҷӯ',
  searchOpportunitiesInfo: [
    'Баробар: <b>abc</b>',
    'Дар аввали сатр: <b>abc*</b>',
    'Содержит: <b>*abc*</b>'
  ].join('<br>'),
  numericSearchOpportunitiesInfo: [
    'Баробар: <b>123</b>',
    'Бештар: <b>&gt;123</b>',
    'Камтар: <b>&lt;123</b>'
  ].join('<br>'),

  no_filter: 'Бе филтр',
  today: 'Имрӯз',
  yesterday: 'Дирӯз',
  current_week: 'Дар ин ҳафта',
  this_month: 'Дар ин моҳ',
  this_year: 'Дар ин сол',
  date: 'За дату',
  period: 'Дар давраи',
  attachments: 'Вложения',
  from_date: 'Аз санаи',
  to_date: 'То санаи',
  areYouSure: 'Шумо мутмаин ҳастед??',
  formWasChanged: 'Маълумотҳои шакл таҳрир карда шуданд. Шумо мутмаин ҳастед, ки тағиротро барҳам дода, маълумотро нав мекунед?',
  addresses: 'Суроғаҳо',
  recStage: 'Марҳилаи тасдиқ',
  route: 'Маршрут',
  executorTemplateFormTitle: 'Шаблон исполнителей',
  amount: 'Миқдор',
  documentStatus: 'Ҳолати ҳуҷҷат',
  tasks: 'Задания',
  day: 'Рӯз',
  woNumber: 'Бе рақам',
  documents: 'Ҳуҷҷатҳо',
  mainExecutor: 'Сармуҳаррир',
  coExecutor: 'Соисполнитель',
  forInfo: 'Ба маълумот',
  control: 'Назорат',
  signers: 'Ба имзо расид',
  producers: 'Подготовили',
  summary: 'Мундариҷа',
  comment: 'Эзоҳ',
  respDepartment: 'Раёсати масъул',
  respExecutor: 'Пудратчии масъул',
  itemdot: 'П.',
  byTemplate: 'По шаблону',
  register: 'Зарегистрировать',
  signsInDocument: 'Подписи',
  signAction: 'Подписать',
  errNoResSigner: 'Не указан подписант резолюции',
  sendOutDoc: 'Отправить',
  sucSendingMsgTitle: 'Ҳуҷҷат бомуваффақият фиристода шуд',
  sucSendingMsg: 'Документ успешно отправлено в СЭВ',
  archive: 'Бойгонӣ',
  importDoc: 'Импортировать документ',
  sucImportMsgTitle: 'Ҳуҷҷат бомуваффақият ворид карда шуд.',
  sucImportMsg: 'Документ был успешно импортирован из СЭВ',
  filterType: 'Намуди  филтр',
  permits: 'Иҷозатнома',
  analyticDesktop: 'Аналитика',
  validFrom: 'Эътибор аз',
  validTo: 'Эътибор то',
  organization: 'Ташкилот',
  email: 'E-Mail',
  name: 'Название',
  issued: 'Выдано',
  documentWasChangedSinceSign: 'Ҳуҷҷат пас аз имзо тағир карда шуд',
  documentWasUnchangedSinceSign: 'Ҳуҷҷат пас аз имзо имзо тағир наёфтааст',
  failedToVerifySignature: 'Невозможно проверить подпись, так как родительский сертификат не доступен',
  notValidCertificate: 'Шаҳодатнома нодуруст аст',
  notTrustedCertificate: 'Сертификат и его родительские сертификаты не принадлежат группе доверительных сертификатов',
  unknownSigner: 'Личность подписанта документа не установлена',
  successfullCertificateValidation: 'Сертификат проверено успешно',
  clockOnSignerComputer: 'Вақти имзошуда мувофиқи вақти дар компютер нишон дода мешавад',
  cannotVerifyTimeStamp: 'Имзо мӯҳлат дорад, аммо тафтиш карда намешавад.',
  verificationResult: 'Результат проверки',
  reason: 'Сабаб',
  location: 'Ҷойгиршавӣ',
  author: 'Муаллиф',
  signVerification: 'Тафтиши имзо',
  // signsInDocument: 'Подписи в документе',
  UserWithoutOrgEmployeeNotAllowed: 'Пользователь не состоит в штате организации (не сопоставлен со штатной единицей). Вход запрещён.',
  // search form (UBPreFilter)
  search: 'Ҷустуҷӯ',
  'Filter by': 'Фильтровать по',
  // cancel: 'Отмена',
  filterForm: 'Шакли ҷустуҷӯ',
  main: 'Основное',
  other: 'Другое',
  showPreFilter: 'Намуди шакли ҷустуҷӯро нишон диҳед',
  editSelItem: 'Редактировать выбранный элемент',
  addNewItem: 'Добавить новый',
  selectFromDictionary: 'Выбрать из справочника',
  clearSelection: 'Очистить',

  isNull: 'Пусто',
  by_value: 'Баробар',
  by_several_value: 'Яке аз',
  more: 'Бештар',
  less: 'Камтар',
  equal: 'Баробар',
  range: 'Диапазон',
  contains: 'Дарбар мегирад',
  startWith: 'Оғоз бо',
  attention: 'Огоҳ',
  doNotSelectedConfigName: 'Танзимот интихоб нашудааст',
  load: 'Загрузить',
  save: 'Сохранить',
  apply: 'Применить',
  doNotSave: 'Не сохранять',
  fDelete: 'Удалить',
  configurationName: 'Конфигурация',
  isRequiredTip: 'Обязательное для заполнения',
  isMultilangTip: 'Значения на других языках',

  headerSelectCert: 'Шаҳодатномаро интихоб кунед',
  headerSelectOwnCert: 'Шаҳодатномаҳоро, ки ба калиди хусусӣ мувофиқанд, интихоб кунед',
  invalidPrivateKeyCertificateSelection: 'Для операции подписания хранилище сертификатов пользователя должно содержать один сертификат. Обратитесь к администратору системы.',

  storageFrmCaption: 'Параметры хранилища',
  storageFrmKeys: 'Калидҳо',
  storageFrmPass: 'Гузарвожа',
  storageFrmPath: 'Хранилище ключей',
  storageFrmBadSorage: 'Гузарвожа ё анбори нодуруст ворид карда шудааст',

  actionDelete: 'Удалить',
  actionAdd: 'Илова кардан',
  captionCert: 'Cертификат',
  actionSelect: 'Интихоб кардан',
  actionCancel: 'Отменить',
  entityLockedOwn: 'Установлена блокировка',
  changedByAnotherUserForLock: 'Ҳангоми дидани ҳуҷҷат, он аз ҷониби истифодабарандаи дигар тағир дода шуда буд. Ҳуҷҷатро боз барои оғози таҳрир дар ҳолати қулфи истисноӣ боз кунед.',

  btnIItSttings: 'Параметры ИИТ',
  btnIItCert: 'Сертификаты ИИТ',
  deleteConfirm: 'Шумо мутмаин ҳастед, ки мехоҳед конфигуратсияро нест кунед??',
  filterWasChangedConfirm: 'Фильтр изменился. При загрузке конфигурации все изменения будут потеряны. Продолжить загрузку?',
  filterIsRequired: 'Фильтр обязательный для заполнения',
  startSearchMinCharacters: 'Минимальное к-во символов для поиска: {0}',
  moreThanOneUserWithPassedCertificate: 'Шаҳодатномаи мазкур аз ҷониби якчанд корбар истифода мешавад. Лутфан номи истифодабарандаро ворид кунед.',
  OpenIDConnect: 'OpenID',
  authOpenIDConnectFail: 'Мақоми сертификатсия дархости тасдиқкуниро рад кард',
  navShortcutCode: 'Код ярлыка',
  navShortcutRights: 'Права на ярлык',
  cases: 'Падежи',
  nameInGen: 'Название в род. падеже',
  nameInDat: 'Название в дат. падеже',
  fullNameInGen: 'Полн. название в род. падеже',
  fullNameInDat: 'Полн. название в дат. падеже',
  Language: 'Язык',
  showDocVersions: 'Предыдущие версии',
  selectDocRevision: 'Выберите версию:',
  isLastDocRevision: '(текущая версия)',
  formShowDocRevisions: 'Версии документа',
  onlyCurrentVersionExists: 'Предыдущих версий документа не обнаружено',
  revisionNum: 'Версия №',

  menu: 'Меню',
  documentNotFound: 'Данные на сервере не найдены. Обратитесь, пожалуйста, к администратору системы.',
  mi_dateFrom: 'Сана аз',
  mi_dateTo: 'Сана то',
  mi_modifyDate: 'Отредактировано',
  ubErrLockedbyanotheruser: 'Сабтро истифодабарандаи дигар қулф задааст. Ҳама тағиротҳои воридшуда захира намешаванд.  Попробуйте позднее.',
  showFilterPanel: 'Филтр',

  print: 'чоп кардан',
  generalInfo: 'Маълумоти умумӣ',
  sexType: 'Ҷинс',
  lastName: 'Насаб',
  firstName: 'Ном',
  middleName: 'Номи падар',
  additionalInfo: 'Маълумоти иловагӣ',
  birthDate: 'Зодрӯз',
  shortFIO: 'Ному насаби кӯтоҳ',
  fullFIO: 'Ному насаби пурра',
  identificationCode: 'РМА',
  identificationCodeShort: 'РМА',
  appeal: 'Обращение',
  appealToPerson: 'Обращение к персоне',
  user: 'Истифодабаранда',
  userOfSystem: 'Истифодабарандаи система',
  enterCommentForRecord: 'Введите комментарий к записи',
  showAudit: 'Аудит',
  calcRowCount: 'Подсчитать количество строк',
  totalRowCount: 'Общее количество строк',

  noPaperInScanner: 'Лоток сканера пуст или сканер неверно настроен. Добавьте документ в лоток и нажмите ОК.',
  doYouWantResume: 'Отсканировать еще страницы?',
  scan: 'Сканирование',

  doScanPages: 'Отсканировано {0} страницу(ы)',
  doRecognizePages: 'Распознается страница № {0}',
  ScannerNotConfigured: 'На вашем компьютере не найдено настроенных сканеров или они не зарегистрированы в системе',
  doStartScan: 'Запрос к сканеру ...',
  doFinishScan: 'Получение результата сканирования',

  serverIsBusy: 'Сервер временно недоступен',
  ubErrRecordmodified: 'Аз лаҳзаи кушодани ин маълумот, истифодабарандаи дигар тағйирот ворид кард. Барои гирифтани маълумоти охирин, "Навсозӣ" -ро пахш кунед.',
  doYouWantFillOtherAttr: 'Вы хотите заполнить другие атрибуты для "{0}" в справочнике "{1}"?',
  comboBoxSaveDictItem: 'Сохранить в справочник',
  selectFtsConnection: 'Область поиска',
  ftsConnectionftsDefault: 'Общая',
  ftsConnectionftsSubjectSearch: 'Субъект',
  ftsFieldCaption: 'Название',
  ftsFieldSnippet: 'Найдено',
  fullTextSearchWidgetResultTitle: 'Результат полнотекстового поиска по запросу <b>{0}</b>',
  ftsTextFieldLabel: 'Дархост',
  ftsChkFilterPeriod: 'Ограничить период',
  ftsSearchGroup: 'Полнотекстовый поиск',
  ftsFilterName: 'Полнотекстовый поиск: {0}',
  fullTextSearchInfo: 'Полнотекстовый поиск по всем данным, которые были включены в поисковый индекс. Как пользоваться ...',
  informationHeader: 'Маълумот',
  elementIsNotActual: 'Элемент не актуален на текущую дату.',

  selectPeriod: 'Выберите период',
  periodType: 'Период',
  periodNone: 'За все время',
  periodDate: 'Рӯз',
  periodChkTwoDay: 'Несколько дней',
  periodMonth: 'Моҳ',
  periodYear: 'Сол',
  periodChkTwoMonth: 'Несколько месяцев',
  periodChkTwoYear: 'Несколько лет',
  emptyPeriod: 'За все время',
  editMultiLang: 'На других языках',

  close: 'Закрыть',
  closeOther: 'Закрыть все, кроме этого',
  closeAll: 'Ҳамаашро пӯшед',

  dropZoneOneFileRequired: 'Барои ин амал танҳо як файл метавонад истифода шавад.',
  dropZoneReplace: 'Ивваза кардан',
  dropZoneAdd: 'Илова кардан',
  dropZoneOperationComplete: 'Файл успешно присоединён',
  downloadAttach: 'Загрузить',

  countST: 'Количество записей',
  sumST: 'Сумма',
  maxST: 'Арзиши максималӣ',
  minST: 'Арзиши минималӣ',
  avgST: 'Арзиши миёна',

  selectedElements: 'Выбранные элементы',
  allElements: 'Все элементы',
  selectElements: 'Выбор элементов',
  selectAll: 'Выбрать все',
  selectAllOnPage: 'Выбрать все элементы на странице',

  preViewInPDF: 'Просмотреть в формате PDF',

  ubErrTheServerHasExceededMaximumNumberOfConnections: 'Сервер превысил максимальное число подключений',
  ubErrFtsForAppDisabled: 'fts для текущего приложения отключен',
  Transformation: 'Конвертация',

  showPlanAndFact: 'Показать план и факт',

  registrationPassed: 'Сертификати шумо бо муваффақият бор карда шуд ва барои коркард пешниҳод карда шуд.',
  registraionPassed: 'Сертификати шумо бо муваффақият бор карда шуд ва барои коркард пешниҳод карда шуд.',
  keyAlreadyRegisteredForUser: 'Калид аллакай барои як корманди дигар ба қайд гирифта шудааст',
  keyBlockedByAdmin: 'Администратор заблокировал использование ключа для входа в систему. Основание для блокировки: ',
  keyNoRightsRejected: 'Истифодабаранда ҳуқуқ надорад, ки бо система кор кунад. Дархост барои бақайдгирии калид рад карда мешавад.',
  keyNoRightsRepeat: 'Истифодабаранда ҳуқуқ надорад, ки бо система кор кунад. Дархост барои бақайдгирии дубораи калид баррасӣ мешавад.',
  keyAlreadyRegistered: 'Аризаи бақайдгирии калидро фиристода наметавонад. Ин калид аллакай дар система сабт шудааст.',

  UbPreFilterMainGroup: 'По атрибутам',

  // mxGraph (org chart)
  'Undo': 'Undo',
  'Redo': 'Redo',
  'Zoom': 'Zoom',
  'Zoom Out': 'Zoom Out',
  'Actual Size': 'Actual Size',
  'Print': 'Print',
  'Poster Print': 'Poster Print',
  'Enter maximum page count': 'Enter maximum page count',
  'Select': 'Select',
  'Pan': 'Pan',
  'Select all': 'Select all',
  'New organizational chart': 'New organizational chart',
  'Create child': 'Create child',
  'Open subordinate chart from this node': 'Open subordinate chart from this node',
  'Remove all child': 'Remove all child',
  'Select all child': 'Select all child',
  'Align child to right': 'Align child to right',
  'Align child down me': 'Align child down me',
  'Format edge top to bottom': 'Format edge top to bottom',
  'Format edge left to right': 'Format edge left to right',
  'Format edge orthogonal': 'Format edge orthogonal',
  'Fit': 'Fit',
  'Overview': 'Overview',
  'Organization': 'Organization',
  'Collapse': 'Collapse',
  'Expand': 'Expand',
  'Append element': 'Append element',
  'Root is not found': 'Root is not found',
  'A4 portrait': 'A4 portrait',
  'A4 landscape': 'A4 landscape',
  'A5 portrait': 'A5 portrait',
  'A5 landscape': 'A5 landscape',
  'Chart for this item does not exist. Create a new one?': 'Chart for this item does not exist. Create a new one?',
  // mxGraph (ER-diagram)
  'toolbar': 'toolbar',
  'entities': 'entities',
  'AsTable': 'AsTable',
  'AsJSON': 'AsJSON',
  'Attributes': 'Attributes',
  'code': 'code',
  'caption': 'caption',
  'dataType': 'dataType',
  'size': 'size',
  'associatedEntity': 'associatedEntity',
  'accessType': 'accessType',
  'allowNull': 'allowNull',
  'isUnique': 'isUnique',
  'defaultValue': 'defaultValue',
  'allowSort': 'allowSort',
  'Mixins': 'Mixins',
  'enabled': 'enabled',

  dateIsTooEarly: 'Дата должна быть больше {0}',
  
  quickAccessButtons: 'Quick access buttons', // TO DO: locale

  showFullScreen: 'Show full screen',

  // !!!
    // Do not change this last item.
    // Put your new items before EOF for SVN auto merge reason.
  EOF: 'EOF'
})

/**
 * ExtJS Tg translation
 */
if (typeof Ext !== 'undefined') {
  Ext.onReady(function () {
    if (Ext.Updater) {
      Ext.Updater.defaults.indicatorText = '<div class="loading-indicator">Идет загрузка...</div>'
    }

    if (Ext.view.View) {
      Ext.view.View.prototype.emptyText = '&lt Нет данных &gt'
    }

    if (Ext.grid.Panel) {
      Ext.grid.Panel.prototype.ddText = '{0} выбранных строк'
    }

    if (Ext.TabPanelItem) {
      Ext.TabPanelItem.prototype.closeText = 'Закрыть эту вкладку'
    }

    if (Ext.form.field.Base) {
      Ext.form.field.Base.prototype.invalidText = 'Значение в этом поле неверное'
    }

    if (Ext.LoadMask) {
      Ext.LoadMask.prototype.msg = 'Загрузка...'
      Ext.LoadMask.msg = 'Загрузка...'
    }

    if (Ext.Date) {
      Ext.Date.monthNames = [
        'Январ',
        'Феврал',
        'Март',
        'Апрел',
        'Май',
        'Июнь',
        'Июль',
        'Август',
        'Сентябр',
        'Октябр',
        'Ноябр',
        'Декабр'
      ]

      Ext.Date.shortMonthNames = [
        'Янв',
        'Февр',
        'Март',
        'Апр',
        'Май',
        'Июнь',
        'Июль',
        'Авг',
        'Сент',
        'Окт',
        'Нояб',
        'Дек'
      ]

      Ext.Date.getShortMonthName = function (month) {
        return Ext.Date.shortMonthNames[month]
      }

      // noinspection NonAsciiCharacters
      Ext.Date.monthNumbers = {
        'Янв': 0,
        'Фев': 1,
        'Мар': 2,
        'Апр': 3,
        'Май': 4,
        'Июн': 5,
        'Июл': 6,
        'Авг': 7,
        'Сен': 8,
        'Окт': 9,
        'Ноя': 10,
        'Дек': 11
      }

      Ext.Date.getMonthNumber = function (name) {
        return Ext.Date.monthNumbers[name.substring(0, 1).toUpperCase() + name.substring(1, 3).toLowerCase()]
      }

      Ext.Date.dayNames = [
         'Якшанбе ',
         'Душанбе',
         'Сешанбе',
         'Чоршанбе',
         'Панҷшанбе',
         'Ҷумъа',
         'Шанбе'
      ]

      Ext.Date.getShortDayName = function (day) {
        return Ext.Date.dayNames[day].substring(0, 3)
      }
    }

    if (Ext.MessageBox) {
      Ext.MessageBox.buttonText = {
        ok: 'OK',
        cancel: 'Отмена',
        yes: 'Ҳа',
        no: 'Не'
      }
      Ext.MessageBox.titleText = {
        confirm: 'Подтверждение',
        prompt: 'Маълумот',
        wait: 'Ҷамъоварӣ ...',
        alert: 'Огоҳ'
      }
    }

    if (Ext.view.AbstractView) {
      Ext.view.AbstractView.prototype.loadingText = 'Загрузка...'
    }

    if (Ext.util.Format) {
      Ext.apply(Ext.util.Format, {
        thousandSeparator: ' ',
        decimalSeparator: ',',
        currencySign: '',
        dateFormat: 'd.m.Y',
        timeFormat: 'G:i:s',
        datetimeFormat: 'd.m.Y H:i'
      })
    }

    Ext.define('Ext.ru.ux.DateTimePicker', {
      override: 'Ext.ux.DateTimePicker',
      todayText: 'Имруз',
      timeLabel: 'ЧЧ  мм'
    })

    if (Ext.picker.Date) {
      Ext.apply(Ext.picker.Date.prototype, {
        todayText: 'Имруз',
        minText: 'Ин сана аз санаи ҳадди аққал барвақттар аст.',
        maxText: 'Ин сана дертар аз санаи максималӣ мебошад.',
        disabledDaysText: '',
        disabledDatesText: '',
        monthNames: Ext.Date.monthNames,
        dayNames: Ext.Date.dayNames,
        nextText: 'Моҳи оянда (Control+Ба тарафи рост)',
        prevText: 'Моҳи гузашта (Control+Ба тарафи чап)',
        monthYearText: 'Интихоби моҳ (Control+Барои интихоб кардани сол ба боло / поён )',
        todayTip: '{0} (Пробел)',
        format: 'd.m.Y',
        altFormats: 'dmY|dmy|d.m.y|d/m/Y|j/m/y|d/n/y|j/m/Y|d/n/Y|d-m-y|d/m|d-m|dm|dmy|dmY|d',
        startDay: 1
      })
    }

    if (Ext.picker.Month) {
      Ext.apply(Ext.picker.Month.prototype, {
        okText: '&#160;OK&#160;',
        cancelText: 'Отмена'
      })
    }

    if (Ext.toolbar.Paging) {
      Ext.apply(Ext.PagingToolbar.prototype, {
        beforePageText: 'Страница',
        afterPageText: 'из {0}',
        firstText: 'Саҳифаи аввал',
        prevText: 'Саҳифаи гузашта',
        nextText: 'Саҳифаи навбатӣ',
        lastText: 'Саҳифаи охирин',
        refreshText: 'Обновить',
        displayMsg: 'Отображаются записи с {0} по {1}, всего {2}',
        emptyMsg: 'Ягон маълумот барои нишон додан нест'
      })
    }

    if (Ext.form.field.Text) {
      Ext.apply(Ext.form.field.Text.prototype, {
        minLengthText: 'Дарозии ҳадди аққали ин соҳа {0}',
        maxLengthText: 'Дарозии максималии ин соҳа {0}',
        blankText: 'Это поле обязательно для заполнения',
        regexText: '',
        emptyText: null
      })
    }

    if (Ext.form.field.Number) {
      Ext.apply(Ext.form.field.Number.prototype, {
        minText: 'Значение этого поля не может быть меньше {0}',
        maxText: 'Значение этого поля не может быть больше {0}',
        nanText: '{0} не является числом'
      })
    }

    if (Ext.form.field.Date) {
      Ext.apply(Ext.form.field.Date.prototype, {
        disabledDaysText: 'Не доступно',
        disabledDatesText: 'Не доступно',
        minText: 'Сана дар ин майдон бояд дертар бошад.{0}',
        maxText: 'Сана бояд дар ин майдон пештар бошад. {0}',
        invalidText: '{0} санаи дуруст нест - сана бояд дар формат зерин бошад {1}',
        format: 'd.m.Y',
        startDay: 1,
        altFormats: 'dmY|dmy|d.m.y|d/m/Y|j/m/y|d/n/y|j/m/Y|d/n/Y|d-m-y|d/m|d-m|dm|dmy|dmY|d'
      })
    }

    if (Ext.form.field.ComboBox) {
      Ext.apply(Ext.form.field.ComboBox.prototype, {
        valueNotFoundText: undefined
      })
      Ext.apply(Ext.form.field.ComboBox.prototype.defaultListConfig, {
        loadingText: 'Загрузка...'
      })
    }

    if (Ext.form.field.VTypes) {
      Ext.apply(Ext.form.field.VTypes, {
        emailText: 'Это поле должно содержать адрес электронной почты в формате "user@example.com"',
        urlText: 'Это поле должно содержать URL в формате "http:/' + '/www.example.com"',
        alphaText: 'Это поле должно содержать только латинские буквы и символ подчеркивания "_"',
        alphanumText: 'Это поле должно содержать только латинские буквы, цифры и символ подчеркивания "_"'
      })
    }

    if (Ext.form.field.HtmlEditor) {
      Ext.apply(Ext.form.field.HtmlEditor.prototype, {
        createLinkText: 'Пожалуйста, введите адрес:',
        buttonTips: {
          bold: {
            title: 'Полужирный (Ctrl+B)',
            text: 'Применение полужирного начертания к выделенному тексту.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          italic: {
            title: 'Курсив (Ctrl+I)',
            text: 'Применение курсивного начертания к выделенному тексту.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          underline: {
            title: 'Подчёркнутый (Ctrl+U)',
            text: 'Подчёркивание выделенного текста.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          increasefontsize: {
            title: 'Увеличить размер',
            text: 'Увеличение размера шрифта.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          decreasefontsize: {
            title: 'Уменьшить размер',
            text: 'Уменьшение размера шрифта.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          backcolor: {
            title: 'Заливка',
            text: 'Изменение цвета фона для выделенного текста или абзаца.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          forecolor: {
            title: 'Цвет текста',
            text: 'Изменение цвета текста.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          justifyleft: {
            title: 'Выравнять текст по левому краю',
            text: 'Выравнивание текста по левому краю.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          justifycenter: {
            title: 'По центру',
            text: 'Выравнивание текста по центру.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          justifyright: {
            title: 'Выравнять текст по правому краю',
            text: 'Выравнивание текста по правому краю.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          insertunorderedlist: {
            title: 'Маркеры',
            text: 'Начать маркированный список.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          insertorderedlist: {
            title: 'Нумерация',
            text: 'Начать нумерованный список.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          createlink: {
            title: 'Вставить гиперссылку',
            text: 'Создание ссылки из выделенного текста.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          sourceedit: {
            title: 'Исходный код',
            text: 'Переключиться на исходный код.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          }
        }
      })
    }

    if (Ext.grid.header.Container) {
      Ext.apply(Ext.grid.header.Container.prototype, {
        sortAscText: 'Сортировать по возрастанию',
        sortDescText: 'Сортировать по убыванию',
        lockText: 'Закрепить столбец',
        unlockText: 'Снять закрепление столбца',
        columnsText: 'Столбцы'
      })
    }

    if (Ext.grid.feature.Grouping) {
      Ext.apply(Ext.grid.feature.Grouping.prototype, {
        emptyGroupText: '(Пусто)',
        groupByText: 'Группировать по этому полю',
        showGroupsText: 'Отображать по группам'
      })
    }

    if (Ext.grid.PropertyColumnModel) {
      Ext.apply(Ext.grid.PropertyColumnModel.prototype, {
        nameText: 'Название',
        valueText: 'Значение',
        dateFormat: 'd.m.Y'
      })
    }

    if (Ext.SplitLayoutRegion) {
      Ext.apply(Ext.SplitLayoutRegion.prototype, {
        splitTip: 'Тяните для изменения размера.',
        collapsibleSplitTip: 'Тяните для изменения размера. Двойной щелчок спрячет панель.'
      })
    }

    if (Ext.layout.BorderLayout && Ext.layout.BorderLayout.SplitRegion) {
      Ext.apply(Ext.layout.BorderLayout.SplitRegion.prototype, {
        splitTip: 'Тяните для изменения размера.',
        collapsibleSplitTip: 'Тяните для изменения размера. Двойной щелчок спрячет панель.'
      })
    }

    if (Ext.form.CheckboxGroup) {
      Ext.apply(Ext.form.CheckboxGroup.prototype, {
        blankText: 'Необходимо выбрать хотя бы одну позицию в группе'
      })
    }

    if (Ext.tab.Tab) {
      Ext.apply(Ext.tab.Tab.prototype, {
        closeText: 'Закрыть вкладку'
      })
    }

    if (Ext.form.Basic) {
      Ext.form.Basic.prototype.waitTitle = 'Пожалуйста, подождите...'
    }
  })
}
