/* global Ext UB */
/**
 * UnityBase Tajik translation.
 */
UB.i18nExtend({
  emptyBarcodeSettings: 'Пеш аз истифодаи штрих-код, шумо бояд онро танзим кунед.',
  setScannerSettings: 'Пеш аз истифодаи сканер бори аввал шумо бояд онро танзим кунед. Шумо метавонед <a href="/" onclick="{0} return false;">дар ин ҷой танзим кунед</a>.',
  showResultConfig: 'Намоиши танзимот',
  numberOfSignificantDigits: 'Миқдори аломатҳои муҳим имконпазир аст',
  yearShort: 'р.',
  PastTooLargeText: 'Шумо миқдори калонеро ворид мекунед. Ин амалиёт метавонад вақти зиёдро талаб кунад. Мехоҳед давом диҳед?',
  gridOptimizeWidth: 'Худкори васеъги',
  showDeveloperDetail: 'Тафсилот таҳиякунанда',
  pleaseInputValueToThisField: 'Арзишро пур кунед',
  Audit: 'Аудит',
  gridEmptySelection: 'Ягон сабти бақайдгирӣ интихоб нашудааст.',
  gridItemLink: 'Истинод ба (на пункт)',
  gridCategoryCaption: 'Гурӯҳ',
  gridFavoritesCaption: 'Мунтахаб',
  info: 'Маълумот',
  error: 'Хатогӣ',
  detail: 'Муфассал',
  uk: 'Украинӣ',
  en: 'Англисӣ',
  ru: 'Русӣ',
  az: 'Озарбойҷонӣ',
  tg: 'Тоҷикӣ',
  id: 'Индонезӣ',
  ka: 'Гурҷӣ',
  ky: 'Қирғизӣ',
  formConstructor: 'Конструктори шаклҳо',
  isAutoGeneratedForm: 'Ин шакл ба таври худкор тавлид мешавад.',
  formNotFound: 'Шакл ёфт нашуд',
  requiredField: 'Ин майдон ҳатмист барои пур кардан',
  General: 'Умумӣ',
  missingDescriptionAttribute: "Амволи  'descriptionAttribute': '{0}'объект ягон хусусияти '{1}' ғайримуқаррариро нишон медиҳад",
  userSettings: 'Танзимот',
  Desktop: 'Мизи корӣ',
  unknownCommand: 'Дастурамали номаълум',
  unknownCommandType: 'Намуди дастурамали номаълум',
  unknownEntityInCommand: 'Дастур нодуруст тавсиф карда шудааст "{0}" барои моҳиятан "{1}". Атрибут entity нодуруст аст.',
  Entity: 'Моҳият',
  Copy: 'Нусхабардоштан',
  Edit: 'Вироштан',
  Delete: 'Ҳавз кардан',
  vseDeystviya: 'Ҳама амалҳо',
  saveAndClose: 'Захира кардан ва пӯшиданд',
  storedData: 'Маълумоти захирашуда',
  resetGUIToDefault: 'Танзимоти интерфейс "бо нобаенӣ"',
  clearLocalStore: 'Тозакунии анбори локалӣ',
  novajaVersija: 'Нусхаи нав',
  aktualnoS: 'Аз __________ муҳим аст',
  refresh: 'Навсозӣ',
  obrazDocumenta: 'Тасвири ҳуҷҷат',
  link: 'Истинод',
  External: 'Берунӣ',
  ChangesHistory: 'Таърихи тағйирот',
  Details: 'Тафсилот',
  Filter: 'Филтр',
  s: 'аз',
  po: 'то',
  pluginNeUstanovlen: 'Плагин насб нашудааст',
  pluginNedostupen: 'Плагин дастнорас аст',
  nastroykiSkanera: 'Танзимоти сканер',
  skanirovat: 'Скан кардан',
  skanirovanieAtributa: 'Сканкунии хусусият',
  izFayla: 'Аз файл',
  shtrikhKod: 'Штрих-код',
  dokument: 'Ҳуҷҷат',
  fayl: 'Файл',
  pleaseWait: 'Лутфан мунтазир шавед...',
  loadingData: 'Боркунии маълумот...',
  zagruzka: 'Боркунӣ...',
  emptyContent: 'Мундариҷа таъин нашудааст',
  vyHotiteUdalitSoderzhimoeDocumenta: 'Оё мутмаинед, ки мехоҳед мундариҷаи ин ҳуҷҷатро нест кунед?',
  vyberiteFayl: 'Файлро интихоб кунед',
  dobavlenie: 'илова кардан',
  serverVremennoNedostupen: 'Сервер муваққатан дастнорас аст. Баъдтар бори дигар кӯшиш кунед ё бо мудири система тамос гиред.',
  deletionDialogConfirmCaption: 'Тозакуниро тасдиқ кунед',
  deleteConfirmation: "Нест кардани сабт аз '{0}'. Шумо мутмаин ҳастед?",
  deleteConfirmationWithCaption: "Воридот нест карда мешавад {1} из '{0}'. Шумо мутмаин ҳастед?",
  deleteFormConfirmCaption: "Ҳавз карда мешавад '{0}'. Шумо мутмаин ҳастед?",
  rowEditing: 'Лозим аст, ки таҳрири маълумотро ба анҷом расонед',
  notValidForColumns: "Арзишҳои нодуруст дар сутунҳои {0}",
  vyUvereny: 'Шумо мутмаин ҳастед?',
  formDefinition: 'Тавсифи интерфейс',
  formModule: 'Тавсифи усулҳо',
  err_line: 'Сатр',
  err_character: 'Сутун',
  err_description: 'Тавсифи хатоги',
  konsolOshibok: 'Консоли хатагиҳо',
  accessRight: 'Иҷозатнома',
  vybrat: 'Интихоб кунед',
  redactirovat: 'Таҳрир кардан',
  addShortcut: 'Илова кардани миёнабур',
  addFolder: 'Илова кардани ҷувздон',
  showPreview: 'Намоиш',
  exportXls: 'Содирот ба "Excel"',
  exportCsv: 'Содирот ба CSV',
  exportHtml: 'Содирот ба Html',
  'export': 'Содирот',
  readPKCanceled: 'Истифодаба қатъ кард',
  invalidPrivateKeyCertificate: 'Шаҳодатномаи(ҳои) нодурусти калиди хусусӣ  интихоб карда шуд. Барои калиди пас аз соли 2014 додашуда бояд ду шаҳодатнома дошта бошад.',
  currentPageNumber: 'Саҳифаи ҷорӣ',

  da: 'Ҳа',
  net: 'Не',
  showLetters: 'Намоиши амомат',
  tabsCountLimitExceeded: 'Аз ҳад зиед ҷадвалбандиҳо кушода аст',
  unsavedData: 'Додаҳо захира нашудаанд',
  confirmFormClosing: 'Тағирот захира карда нашуд. Закрыть форму <b>с потерей введённых изменений</b>?',
  confirmSave: 'Мехоҳед тағиротро захира кунед?',
  original: 'Аслӣ',
  ot: ' аз ',
  do: ' то ',
  document: 'Ҳуҷҷат',
  sign: 'Ворид шуданд',

  NMUBExtension: 'васеъшавии "UBExtension"',
  NMFeatureScanner: 'Модули дастгирии скан',
  NMFeatureDSTU: 'Модули рамзгузорӣ ДСТУ',
  NMFeatureIIT: 'Модули дастгирӣ ЭЦП ИИТ',
  NMFeaturePDFSigner: 'Модули имзо PDF',
  singOperationInProcess: 'Як санади дигар имзо шуда истодааст. Баъдтар дубора сайъ кунед',

    // all messages below are formatted with 4 params [0=UB.i18n(featureInfo.UIName), 1=featureInfo.minVersion, 2=currentVersion, 3=installerDownloadPath]
  NMInstallExtensionChrome: '<p>Барои идома додани кор, шумо бояд як тавсеаи <b>"UBExtension"</b> браузери Google Chrome-ро насб кунед.</p> ' +
        '<p>Истинодро клик кунед <a href="https://chrome.google.com/webstore/detail/ubextension/{3}" target="_blank">БАРНОМАИ ЁРИДАХАНДА-ро</a> ' +
        ' барои гузаштан ба мағозаи Google</p>' +
        '<p> Дар равзанаи мағоза тугмаи <img src="models/adminui-pub/ub-extension/ChromePlusFreeEn.png"/> -ро пахш кунед (шояд <b>+РОЙГОН</b>)</p>' +
        '<p>Равзана пайдо мешавад, ки насби васеъшавиро тасдиқ мекунад - "Илова" -ро клик кунед (Add).</p>' +
        '<p>Васеъ насб карда мешавад ва тугмаи <b>+FREE</b> сабз хоҳад шуд:  <img src="models/adminui-pub/ub-extension/ChromeAddedEn.png"/> ' +
        '<p>Пас аз насб кардани васеъкунӣ <b>браузери худро аз нав дароред! </b></p>',
  NMInstallExtensionOpera: '<p>Барои идома додан, шумо бояд васеъкуниро насб кунед <b>"UBExtension"</b> барои браузери Opera.</p> ' +
        '<p>Истинодро клик кунед <a href="models/adminui-pub/ub-extension/UBExtension.crx" target="_blank">БАРНОМАИ ЁРИДАХАНДА-ро</a>.</p>' +
        '<p>Браузер тамдидро зеркашӣ мекунад ва ба шумо дар болои экран паём медиҳад. ' +
        'Дар панели огоҳӣ тугмачаи "Go" -ро (Гузаштан) пахш кунед- Opera саҳифаеро бо васеъкунакҳо насб мекунад. Он ҷо "UBExtension" -ро ёбед ва "Install" -ро (Насб) пахш намоед.</p> ' +
        '<p>Баъд аз ин, насб ба анҷом расидааст ва шумо бояд браузерро аз нав оғоз кунед.</p>',
  NMUpdateExtensionChrome: '<p>Барои идома додан, шумо бояд навсозӣ кунед <b>{0}</b> то версия-и <i>{2}</i>.</p> ' +
        '<p>Одатан браузери Google Chrome васеъкуниҳоро ба таври худкор нав мекунад. Кӯшиш кунед, бори дигар тугмачаи пӯшед / кушоед пахш намоед.' +
        ' Барои навсозиҳои дастӣ ба мағозаи Google бо ин пайванд <a href="https://chrome.google.com/webstore/detail/ubextension/{3}" target="_blank">гузаред</a> </p>',
  NMUpdateExtensionOpera: '<p>Барои идома додан, шумо бояд навсозӣ кунед <b>{0}</b> то версияи <i>{2}</i>.</p> ' +
        '<p>Одатан, браузери Opera васеъшавиро ба таври худкор навсозӣ мекунад. Кӯшиш кунед, бори дигар браузерро пӯшед / кушоед пахш намоед. ' +
        ' Барои навсозии дастӣ, ба <a href="models/adminui-pub/ub-extension/UBExtension.crx" target="_blank">ин истинод клик кунед</a> </p>',
  NMInstallFeature: '<p>Барои истифодаи ин функсия, шумо бояд насб кунед <b>{0}</b>.</p> ' +
        '<p>Истинодро клик кунед <a href="{3}" target="_blank">ЗАГРУЗИТЬ ИНСТАЛЛЯЦИЮ</a>. Пас аз он, ки зеркашӣ анҷом ёфтааст, насбкуниро оғоз кунед ва мувофиқи дастурҳо амал намоед.</p>' +
        '<p>Пас аз он ки насбкунӣ ба анҷом расад, шумо бояд браузерро аз нав ба кор дароред.</p>',
  NMUpdateFeature: '<p>Версияи нав таҳия карда шуд <i>{1}</i> приложения <b>{0}</b>.</p> ' +
        '<p>Истинодро клик кунед <a href="{3}" target="_blank">ЗАГРУЗИТЬ ОБНОВЛЕНИЕ</a>.  Пас аз он, ки зеркашӣ тамом мешавад, навсозиро оғоз кунед ва мувофиқи дастурҳо иҷро намоед.</p>' +
        '<p>Пас аз навсозӣ ба анҷом расида, шумо бояд браузерро аз нав оғоз намоед.</p>',

  clear: 'Тоза кардан',
  signed: 'Имзо гузаронидан',
  term: 'Мӯҳлат',
  executed: 'Иҷро шуд',
  linkToDocItem: 'Банди ҳуҷҷат',
  filter: 'Филтр',
  doubletAlertTitle: 'Нусхаҳои дигари ҳуҷҷат',
  doubletAlertMsg: 'Нусхаҳои дуюми ҳуҷҷатҳо пайдо шуданд: {0}. Шумо мехоҳед идома диҳед?',
  barcodeRegData: '{0} аз {1}',
  barcodeSheets: 'варақ.{0}',
  withoutNumber: 'Б/Н',
  withoutDate: 'Б/Д',
  partialDataLoaded: 'Маълумот қисман зеркашӣ карда шуд. Барои дидани ҳамаи вурудот дар ин ҷо пахш кунед',
  include: ' дар бар мегирад',
  tooManyItems: 'Вурудоти аз ҳад зиёд. Лутфан кӯшиш кунед, ки ҷустуҷӯятонро дақиқ кунед.',
  fetchAllRows: 'Ҳамаро зеркашӣ кунед',
  rowCounts: 'Эзоҳҳо',
  doNotGetLock: 'Навишта тавассути истифодакунандаи {0} {1} сония пеш масдуд карда шудааст. Дертар саъй кунед..',
  persistLockInfo: 'Баста шудааст {1}',
  softLockInfo: 'Тавассути истифодакунандаи {0} дар {1} масдуд карда шудааст',
  lockBtn: 'Навишта масдуд карда шавад',
  unLockBtn: 'Навишта аз ҳолати масдудшудабароварда шавад',
  tempSoftLockInfo: 'Ҳоло сабтро корбар таҳрир кардааст. {0}',
  recordLockedOtherUser: 'Навишта масдуд карда шуд бо истифодабарандаи дигар',
  recordLockedThisUser: 'Сабт аллакай баста шудааст',
  lockSuccessCreated: 'Сабт бо муваффақият баста шуд',
  recordLockedByTempLock: 'Ин мактубро корбари дигар таҳрир карда истодааст.',
  recordLockedThisUserByTempLock: 'Истифодабарандаи ҷорӣ сабтро таҳрир карда истодааст.',
  lockSuccessDeleted: 'Навишта бомуваффақият аз ҳолати масдудшуда бароварда шуд',
  recordNotLocked: 'Навишта масдуд карда нашудааст',
  tempLockExistForThisUser: 'Истифодабарандаи ҷорӣ вурудро дар дигар ҷадвал, дар равзанаи дигар ё дар компютери дигар таҳрир карда истодааст.',

  resolutionSignReason: 'Амри хаттӣ имзо шудааст',
  noStaffEmployeeShortFIO: 'Таъйин карда нашудааст',
  made: 'Омодашуда аст',
  notSpecified: 'Муайян карда нашудааст',
  forms: 'шаклҳо',
  Forms: 'Шаклҳо',
  searchOpportunities: 'Хусусиятҳои ҷустуҷӯ',
  searchOpportunitiesInfo: [
    'Баробар: <b>abc</b>',
    'Дар аввали сатр: <b>abc*</b>',
    'Дарбар мегирад: <b>*abc*</b>'
  ].join('<br>'),
  numericSearchOpportunitiesInfo: [
    'Баробар: <b>123</b>',
    'Бештар: <b>&gt;123</b>',
    'Камтар: <b>&lt;123</b>'
  ].join('<br>'),

  no_filter: 'Бе филтр',
  today: 'Имрӯз',
  yesterday: 'Дирӯз',
  current_week: 'Дар ин ҳафта',
  this_month: 'Дар ин моҳ',
  this_year: 'Дар ин сол',
  date: 'Барои санаи',
  period: 'Дар давраи',
  attachments: 'Замимаҳо',
  from_date: 'Аз санаи',
  to_date: 'То санаи',
  areYouSure: 'Шумо мутмаин ҳастед?',
  formWasChanged: 'Маълумотҳои шакл таҳрир карда шуданд. Шумо мутмаин ҳастед, ки тағиротро барҳам дода, маълумотро нав мекунед?',
  addresses: 'Суроғаҳо',
  recStage: 'Марҳилаи тасдиқ',
  route: 'Масир',
  executorTemplateFormTitle: 'Шаблон исполнителей',
  amount: 'Миқдор',
  documentStatus: 'Ҳолати ҳуҷҷат',
  tasks: 'Вазифаҳо',
  day: 'Рӯз',
  woNumber: 'Бе рақам',
  documents: 'Ҳуҷҷатҳо',
  mainExecutor: 'Иҷрокунанда',
  coExecutor: 'Ҳамиҷрокунанда',
  forInfo: 'Ба маълумот',
  control: 'Назорат',
  signers: 'Ба имзо расид',
  producers: 'Омода кардаанд',
  summary: 'Мундариҷа',
  comment: 'Эзоҳ',
  respDepartment: 'Раёсати масъул',
  respExecutor: 'Пудратчии масъул',
  itemdot: 'П.',
  byTemplate: 'Аз рӯи намуна',
  register: 'Сабт шудан',
  signsInDocument: 'Имзоҳо',
  signAction: 'Имзо гузаронидан',
  errNoResSigner: 'Имзокунандаи қатънома муайян нашудааст',
  sendOutDoc: 'Ирсол намудан',
  sucSendingMsgTitle: 'Ҳуҷҷат бомуваффақият фиристода шуд',
  sucSendingMsg: 'Ҳуҷҷат ба СҲЭ бомуваффақият фиристода шуд',
  archive: 'Бойгонӣ',
  importDoc: 'Ворид кардани ҳуҷҷат',
  sucImportMsgTitle: 'Ҳуҷҷат бомуваффақият ворид карда шуд.',
  sucImportMsg: 'Ҳуҷҷат аз СҲЭ бомуваффақият ворид карда шуд',
  filterType: 'Намуди  филтр',
  permits: 'Иҷозатнома',
  analyticDesktop: 'Таҳлил',
  validFrom: 'Эътибор аз',
  validTo: 'Эътибор то',
  organization: 'Ташкилот',
  email: 'E-Mail',
  name: 'Номгӯй',
  issued: 'Дода шуд',
  documentWasChangedSinceSign: 'Ҳуҷҷат пас аз имзо тағир карда шуд',
  documentWasUnchangedSinceSign: 'Ҳуҷҷат пас аз имзо имзо тағир наёфтааст',
  failedToVerifySignature: 'Санҷидани имзо имконнопазир аст, чунки сертификати волидӣ дастрас нест',
  notValidCertificate: 'Шаҳодатнома нодуруст аст',
  notTrustedCertificate: 'Сертификат ва сертификатҳои волидии он ба гурӯҳи сертификатҳои ваколатӣ мансуб нестанд',
  unknownSigner: 'Шиносаи имзокунанда муайян карда нашудааст',
  successfullCertificateValidation: 'Сертификат бо муваффақият тасдиқ карда шуд',
  clockOnSignerComputer: 'Вақти имзошуда мувофиқи вақти дар компютер нишон дода мешавад',
  cannotVerifyTimeStamp: 'Имзо мӯҳлат дорад, аммо тафтиш карда намешавад.',
  verificationResult: 'Натиҷаи санҷиш',
  reason: 'Сабаб',
  location: 'Ҷойгиршавӣ',
  author: 'Муаллиф',
  signVerification: 'Тафтиши имзо',
  // signsInDocument: 'Имзоҳо дар ҳуҷҷат',
  UserWithoutOrgEmployeeNotAllowed: 'Истифодабаранда узви созмон нест (ба шӯъбаи кормандон муқоиса карда нашудааст). Вуруд манъ аст.',
  // search form (UBPreFilter)
  search: 'Ҷустуҷӯ',
  'Filter by': 'Филтр кардан бо',
  // cancel: 'Бекор кардан',
  filterForm: 'Шакли ҷустуҷӯ',
  main: 'Асосӣ',
  other: 'Ғайра',
  showPreFilter: 'Намуди шакли ҷустуҷӯро нишон диҳед',
  editSelItem: 'Элементҳои интихобшударо таҳрир кунед',
  addNewItem: 'Иловаи нав',
  selectFromDictionary: 'Интихоб аз маълумотнома',
  clearSelection: 'Тоза кардан',

  isNull: 'Холӣ',
  by_value: 'Баробар',
  by_several_value: 'Яке аз',
  more: 'Бештар',
  less: 'Камтар',
  equal: 'Баробар',
  range: 'Диапазон',
  contains: 'Дарбар мегирад',
  startWith: 'Оғоз бо',
  attention: 'Огоҳ',
  doNotSelectedConfigName: 'Танзимот интихоб нашудааст',
  load: 'Зеркашӣ',
  save: 'Захира кардан',
  apply: 'Татбиқ гардад',
  doNotSave: 'Ҳифз карда нашавад',
  fDelete: 'Ҳавз кардан',
  configurationName: 'Танзимот',
  isRequiredTip: 'Ҳатмӣ барои пур кардани',
  isMultilangTip: 'Арзишҳо бо забонҳои дигар',

  headerSelectCert: 'Шаҳодатномаро интихоб кунед',
  headerSelectOwnCert: 'Шаҳодатномаҳоро, ки ба калиди хусусӣ мувофиқанд, интихоб кунед',
  invalidPrivateKeyCertificateSelection: 'Барои амалиёти имзо махзани сертификатҳои истифодакунанда бояд як сертификат дошта бошад. Ба маъмури система муроҷиат кунед.',

  storageFrmCaption: 'Параметрҳои махзан',
  storageFrmKeys: 'Калидҳо',
  storageFrmPass: 'Гузарвожа',
  storageFrmPath: 'Махзани калидҳо',
  storageFrmBadSorage: 'Гузарвожа ё анбори нодуруст ворид карда шудааст',

  actionDelete: 'Ҳавз кардан',
  actionAdd: 'Илова кардан',
  captionCert: 'Cертификат',
  actionSelect: 'Интихоб кардан',
  actionCancel: 'Бекор карда шавад',
  entityLockedOwn: 'Масдудсозӣ гузошта шудааст',
  changedByAnotherUserForLock: 'Ҳангоми дидани ҳуҷҷат, он аз ҷониби истифодабарандаи дигар тағир дода шуда буд. Ҳуҷҷатро боз барои оғози таҳрир дар ҳолати қулфи истисноӣ боз кунед.',

  btnIItSttings: 'Параметры ИИТ',
  btnIItCert: 'Сертификаты ИИТ',
  deleteConfirm: 'Шумо мутмаин ҳастед, ки мехоҳед конфигуратсияро нест кунед?',
  filterWasChangedConfirm: 'Филтр тағир ёфтааст. Ҳангоми бор кардани конфигуратсия, ҳама тағиротҳо гум карда мешаванд. Боркуниро идома диҳед?',
  filterIsRequired: 'Филтр хатминт барои пур намудан',
  startSearchMinCharacters: 'Аломатҳои камтарин барои ҷустуҷӯ: {0}',
  moreThanOneUserWithPassedCertificate: 'Шаҳодатномаи мазкур аз ҷониби якчанд корбар истифода мешавад. Лутфан номи истифодабарандаро ворид кунед.',
  OpenIDConnect: 'OpenID',
  authOpenIDConnectFail: 'Мақоми сертификатсия дархости тасдиқкуниро рад кард',
  navShortcutCode: 'Рамзи миёнабур',
  navShortcutRights: 'Ҳуқуқ ба миёнабур',
  cases: 'Падежи',
  nameInGen: 'Название в род. падеже',
  nameInDat: 'Название в дат. падеже',
  fullNameInGen: 'Полн. название в род. падеже',
  fullNameInDat: 'Полн. название в дат. падеже',
  Language: 'Забон',
  showDocVersions: 'Версияи гузашта',
  selectDocRevision: 'Версияро интихоб кунед:',
  isLastDocRevision: '(версияи ҷорӣ)',
  formShowDocRevisions: 'Версияҳои ҳуҷҷат',
  onlyCurrentVersionExists: 'Версияҳои пештари хуччат ёфт нашуд',
  revisionNum: 'Версияи №',

  menu: 'Меню',
  documentNotFound: 'Дар сервер ягон маълумоте ёфт нашуд. Лутфан бо мудири системаи худ тамос гиред.',
  mi_dateFrom: 'Сана аз',
  mi_dateTo: 'Сана то',
  mi_modifyDate: 'Таҳрир карда шудааст',
  ubErrLockedbyanotheruser: 'Сабтро истифодабарандаи дигар қулф задааст. Ҳама тағиротҳои воридшуда захира намешаванд.  Попробуйте позднее.',
  showFilterPanel: 'Филтр',

  print: 'чоп кардан',
  generalInfo: 'Маълумоти умумӣ',
  sexType: 'Ҷинс',
  lastName: 'Насаб',
  firstName: 'Ном',
  middleName: 'Номи падар',
  additionalInfo: 'Маълумоти иловагӣ',
  birthDate: 'Зодрӯз',
  shortFIO: 'Ному насаби кӯтоҳ',
  fullFIO: 'Ному насаби пурра',
  identificationCode: 'РМА',
  identificationCodeShort: 'РМА',
  appeal: 'Муроҷиат',
  appealToPerson: 'Муроҷиат ба шахс',
  user: 'Истифодабаранда',
  userOfSystem: 'Истифодабарандаи система',
  enterCommentForRecord: 'Тафсири навиштаро ворид намоед',
  showAudit: 'Аудит',
  calcRowCount: 'Миқдори сатрҳо ҳисоб карда шавад',
  totalRowCount: 'Миқдори умумии сатрҳо',

  noPaperInScanner: 'Новадони сканер холӣ аст ё сканер нодуруст танзим гардидааст. Ҳуҷҷатро ба новадон илова намоед ва ОК-ро пахш кунед.',
  doYouWantResume: 'Боз саҳифаҳои дигар скан карда шавад?',
  scan: 'Сканкунӣ',

  doScanPages: 'О{0} саҳифа скан карда шуд',
  doRecognizePages: 'Саҳифаи № {0} шиносоӣ мешавад',
  doRecognizeDocument: 'Разпознается документ ...',
  ScannerNotConfigured: 'Дар компютери Шумо сканерҳои танзимшуда пайдо нашуд ё ин, ки онҳо дар система ба қайд гирифта нашудаанд',
  doStartScan: 'Дархост ба сканери ...',
  doFinishScan: 'Дарёфти натиҷаи сканкунӣ',

  serverIsBusy: 'Сервер муваққатан қобили дастрасӣ нест',
  ubErrRecordmodified: 'Аз лаҳзаи кушодани ин маълумот, истифодабарандаи дигар тағйирот ворид кард. Барои гирифтани маълумоти охирин, "Навсозӣ" -ро пахш кунед.',
  doYouWantFillOtherAttr: 'Шумо мехоҳед дигар хусусиятҳоро барои "{0}" дар маълумотнома пур кунед "{1}"?',
  comboBoxSaveDictItem: 'Дар маълумотнома ҳифз карда шавад',
  selectFtsConnection: 'Соҳаи ҷустуҷӯ',
  ftsConnectionftsDefault: 'Умумӣ',
  ftsConnectionftsSubjectSearch: 'Субъект',
  ftsFieldCaption: 'Номгӯй',
  ftsFieldSnippet: 'Дарефт шуд',
  fullTextSearchWidgetResultTitle: 'Натиҷаи ҷустуҷӯи пурраи матн барои <b>{0}</b>',
  ftsTextFieldLabel: 'Дархост',
  ftsChkFilterPeriod: 'Давра маҳдуд карда шавад',
  ftsSearchGroup: 'Ҷустуҷӯи пурраматн',
  ftsFilterName: 'Ҷустуҷӯи пурраматн: {0}',
  fullTextSearchInfo: 'Ҷустуҷӯи пурраматн аз рӯи тамоми маълумоте, ки ба индекси ҷустуҷӯ дохил карда шуда буд...',
  informationHeader: 'Маълумот',
  elementIsNotActual: 'Унсур дар санаи ҷорӣ муҳим нест.',

  selectPeriod: 'Давраро интихоб намоед',
  periodType: 'Давр',
  periodNone: 'Барои ҳама вақт',
  periodDate: 'Рӯз',
  periodChkTwoDay: 'Якчанд рӯз',
  periodMonth: 'Моҳ',
  periodYear: 'Сол',
  periodChkTwoMonth: 'Якчанд моҳ',
  periodChkTwoYear: 'Якчанд сол',
  emptyPeriod: 'Барои ҳама вақт',
  editMultiLang: 'Бо забонҳои дигар',

  close: 'Пӯшед',
  closeOther: 'Ҳама чизро пӯшед гайр аз ин',
  closeAll: 'Ҳамаашро пӯшед',

  dropZoneOneFileRequired: 'Барои ин амал танҳо як файл метавонад истифода шавад.',
  dropZoneReplace: 'Ивваза кардан',
  dropZoneAdd: 'Илова кардан',
  dropZoneOperationComplete: 'Файл бо муваффақият замима карда мешавад',
  downloadAttach: 'Боргирӣ шавад',

  countST: 'Шумораи сабтҳо',
  sumST: 'Миқдор',
  maxST: 'Арзиши максималӣ',
  minST: 'Арзиши минималӣ',
  avgST: 'Арзиши миёна',

  selectedElements: 'Элементҳои интихобшуда',
  allElements: 'Ҳаммаи элементҳо',
  selectElements: 'Интихоби элементҳо',
  selectAll: 'Ҳамаашро интихоб кунед',
  selectAllOnPage: 'Интихоб кардани ҳамаи элментҳо дар саҳифа',

  preViewInPDF: 'Пешнамоиш дар формати PDF',

  ubErrTheServerHasExceededMaximumNumberOfConnections: 'Сервер миқдори имконпазири пайвастшавиҳоро гузашт.',
  ubErrFtsForAppDisabled: 'fts для текущего приложения отключен',
  Transformation: 'Конвертатсия',

  showPlanAndFact: 'Нишон додани нақша ва далел',

  registrationPassed: 'Сертификати шумо бо муваффақият бор карда шуд ва барои коркард пешниҳод карда шуд.',
  registraionPassed: 'Сертификати шумо бо муваффақият бор карда шуд ва барои коркард пешниҳод карда шуд.',
  keyAlreadyRegisteredForUser: 'Калид аллакай барои як корманди дигар ба қайд гирифта шудааст',
  keyBlockedByAdmin: 'Мудир истифодаи калидро барои ворид шудан ба система масдуд кардааст. Пойгоҳ барои бастан: ',
  keyNoRightsRejected: 'Истифодабаранда ҳуқуқ надорад, ки бо система кор кунад. Дархост барои бақайдгирии калид рад карда мешавад.',
  keyNoRightsRepeat: 'Истифодабаранда ҳуқуқ надорад, ки бо система кор кунад. Дархост барои бақайдгирии дубораи калид баррасӣ мешавад.',
  keyAlreadyRegistered: 'Аризаи бақайдгирии калидро фиристода наметавонад. Ин калид аллакай дар система сабт шудааст.',

  UbPreFilterMainGroup: 'Аз рӯи хусусиятҳо',

  // mxGraph (org chart)
  'Undo': 'Undo',
  'Redo': 'Redo',
  'Zoom': 'Zoom',
  'Zoom Out': 'Zoom Out',
  'Actual Size': 'Actual Size',
  'Print': 'Print',
  'Poster Print': 'Poster Print',
  'Enter maximum page count': 'Enter maximum page count',
  'Select': 'Select',
  'Pan': 'Pan',
  'Select all': 'Select all',
  'New organizational chart': 'New organizational chart',
  'Create child': 'Create child',
  'Open subordinate chart from this node': 'Open subordinate chart from this node',
  'Remove all child': 'Remove all child',
  'Select all child': 'Select all child',
  'Align child to right': 'Align child to right',
  'Align child down me': 'Align child down me',
  'Format edge top to bottom': 'Format edge top to bottom',
  'Format edge left to right': 'Format edge left to right',
  'Format edge orthogonal': 'Format edge orthogonal',
  'Fit': 'Fit',
  'Overview': 'Overview',
  'Organization': 'Organization',
  'Collapse': 'Collapse',
  'Expand': 'Expand',
  'Append element': 'Append element',
  'Root is not found': 'Root is not found',
  'A4 portrait': 'A4 portrait',
  'A4 landscape': 'A4 landscape',
  'A5 portrait': 'A5 portrait',
  'A5 landscape': 'A5 landscape',
  'Chart for this item does not exist. Create a new one?': 'Chart for this item does not exist. Create a new one?',
  // mxGraph (ER-diagram)
  'toolbar': 'toolbar',
  'entities': 'entities',
  'AsTable': 'AsTable',
  'AsJSON': 'AsJSON',
  'Attributes': 'Attributes',
  'code': 'code',
  'caption': 'caption',
  'dataType': 'dataType',
  'size': 'size',
  'associatedEntity': 'associatedEntity',
  'accessType': 'accessType',
  'allowNull': 'allowNull',
  'isUnique': 'isUnique',
  'defaultValue': 'defaultValue',
  'allowSort': 'allowSort',
  'Mixins': 'Mixins',
  'enabled': 'enabled',

  dateIsTooEarly: 'Сана бояд аз {0} зиёд бошад',

  quickAccessButtons: 'Quick access buttons', // TO DO: locale

  showFullScreen: 'Show full screen',

  // !!!
    // Do not change this last item.
    // Put your new items before EOF for SVN auto merge reason.
  EOF: 'EOF'
})

/**
 * ExtJS Tg translation
 */
if (typeof Ext !== 'undefined') {
  Ext.onReady(function () {
    if (Ext.Updater) {
      Ext.Updater.defaults.indicatorText = '<div class="loading-indicator">Идет загрузка...</div>'
    }

    if (Ext.view.View) {
      Ext.view.View.prototype.emptyText = '&lt Маълумот нест &gt'
    }

    if (Ext.grid.Panel) {
      Ext.grid.Panel.prototype.ddText = '{0} сатрҳои интихобшуда'
    }

    if (Ext.TabPanelItem) {
      Ext.TabPanelItem.prototype.closeText = 'Ин ҷадвалро пӯшед'
    }

    if (Ext.form.field.Base) {
      Ext.form.field.Base.prototype.invalidText = 'Маъно дар ин ҳошия нодуруст аст'
    }

    if (Ext.LoadMask) {
      Ext.LoadMask.prototype.msg = 'Боркунӣ...'
      Ext.LoadMask.msg = 'Боркунӣ...'
    }

    if (Ext.Date) {
      Ext.Date.monthNames = [
        'Январ',
        'Феврал',
        'Март',
        'Апрел',
        'Май',
        'Июн',
        'Июл',
        'Август',
        'Сентябр',
        'Октябр',
        'Ноябр',
        'Декабр'
      ]

      Ext.Date.shortMonthNames = [
        'Янв',
        'Февр',
        'Март',
        'Апр',
        'Май',
        'Июн',
        'Июл',
        'Авг',
        'Сент',
        'Окт',
        'Нояб',
        'Дек'
      ]

      Ext.Date.getShortMonthName = function (month) {
        return Ext.Date.shortMonthNames[month]
      }

      // noinspection NonAsciiCharacters
      Ext.Date.monthNumbers = {
        'Янв': 0,
        'Фев': 1,
        'Мар': 2,
        'Апр': 3,
        'Май': 4,
        'Июн': 5,
        'Июл': 6,
        'Авг': 7,
        'Сен': 8,
        'Окт': 9,
        'Ноя': 10,
        'Дек': 11
      }

      Ext.Date.getMonthNumber = function (name) {
        return Ext.Date.monthNumbers[name.substring(0, 1).toUpperCase() + name.substring(1, 3).toLowerCase()]
      }

      Ext.Date.dayNames = [
         'Якшанбе ',
         'Душанбе',
         'Сешанбе',
         'Чоршанбе',
         'Панҷшанбе',
         'Ҷумъа',
         'Шанбе'
      ]

      Ext.Date.getShortDayName = function (day) {
        return Ext.Date.dayNames[day].substring(0, 3)
      }
    }

    if (Ext.MessageBox) {
      Ext.MessageBox.buttonText = {
        ok: 'OK',
        cancel: 'Бекор кардан',
        yes: 'Ҳа',
        no: 'Не'
      }
      Ext.MessageBox.titleText = {
        confirm: 'Тасдиқ додан',
        prompt: 'Маълумот',
        wait: 'Ҷамъоварӣ ...',
        alert: 'Огоҳ'
      }
    }

    if (Ext.view.AbstractView) {
      Ext.view.AbstractView.prototype.loadingText = 'Боркунӣ...'
    }

    if (Ext.util.Format) {
      Ext.apply(Ext.util.Format, {
        thousandSeparator: ' ',
        decimalSeparator: ',',
        currencySign: '',
        dateFormat: 'd.m.Y',
        timeFormat: 'G:i:s',
        datetimeFormat: 'd.m.Y H:i'
      })
    }

    Ext.define('Ext.ru.ux.DateTimePicker', {
      override: 'Ext.ux.DateTimePicker',
      todayText: 'Имруз',
      timeLabel: 'ЧЧ  мм'
    })

    if (Ext.picker.Date) {
      Ext.apply(Ext.picker.Date.prototype, {
        todayText: 'Имруз',
        minText: 'Ин сана аз санаи ҳадди аққал барвақттар аст.',
        maxText: 'Ин сана дертар аз санаи максималӣ мебошад.',
        disabledDaysText: '',
        disabledDatesText: '',
        monthNames: Ext.Date.monthNames,
        dayNames: Ext.Date.dayNames,
        nextText: 'Моҳи оянда (Control+Ба тарафи рост)',
        prevText: 'Моҳи гузашта (Control+Ба тарафи чап)',
        monthYearText: 'Интихоби моҳ (Control+Барои интихоб кардани сол ба боло / поён )',
        todayTip: '{0} (Пробел)',
        format: 'd.m.Y',
        altFormats: 'dmY|dmy|d.m.y|d/m/Y|j/m/y|d/n/y|j/m/Y|d/n/Y|d-m-y|d/m|d-m|dm|dmy|dmY|d',
        startDay: 1
      })
    }

    if (Ext.picker.Month) {
      Ext.apply(Ext.picker.Month.prototype, {
        okText: '&#160;OK&#160;',
        cancelText: 'Бекор кардан'
      })
    }

    if (Ext.toolbar.Paging) {
      Ext.apply(Ext.PagingToolbar.prototype, {
        beforePageText: 'Саҳифа',
        afterPageText: 'из {0}',
        firstText: 'Саҳифаи аввал',
        prevText: 'Саҳифаи гузашта',
        nextText: 'Саҳифаи навбатӣ',
        lastText: 'Саҳифаи охирин',
        refreshText: 'Навсозӣ',
        displayMsg: 'Намоиши вурудот аз {0} то {1}, ҳамагӣ {2}',
        emptyMsg: 'Ягон маълумот барои нишон додан нест'
      })
    }

    if (Ext.form.field.Text) {
      Ext.apply(Ext.form.field.Text.prototype, {
        minLengthText: 'Дарозии ҳадди аққали ин соҳа {0}',
        maxLengthText: 'Дарозии максималии ин соҳа {0}',
        blankText: 'Ин ҳошия барои пур кардан ҳатмӣ аст',
        regexText: '',
        emptyText: null
      })
    }

    if (Ext.form.field.Number) {
      Ext.apply(Ext.form.field.Number.prototype, {
        minText: 'Арзиши ин соҳа набояд аз он камтар бошад {0}',
        maxText: 'Арзиши ин соҳа набояд аз бузургтар бошад {0}',
        nanText: '{0} рақам нест'
      })
    }

    if (Ext.form.field.Date) {
      Ext.apply(Ext.form.field.Date.prototype, {
        disabledDaysText: 'Дастрас нест',
        disabledDatesText: 'Дастрас нест',
        minText: 'Сана дар ин майдон бояд дертар бошад.{0}',
        maxText: 'Сана бояд дар ин майдон пештар бошад. {0}',
        invalidText: '{0} санаи дуруст нест - сана бояд дар формат зерин бошад {1}',
        format: 'd.m.Y',
        startDay: 1,
        altFormats: 'dmY|dmy|d.m.y|d/m/Y|j/m/y|d/n/y|j/m/Y|d/n/Y|d-m-y|d/m|d-m|dm|dmy|dmY|d'
      })
    }

    if (Ext.form.field.ComboBox) {
      Ext.apply(Ext.form.field.ComboBox.prototype, {
        valueNotFoundText: undefined
      })
      Ext.apply(Ext.form.field.ComboBox.prototype.defaultListConfig, {
        loadingText: 'Боркунӣ...'
      })
    }

    if (Ext.form.field.VTypes) {
      Ext.apply(Ext.form.field.VTypes, {
        emailText: 'Ин майдон бояд суроғаи почтаи электронӣ дошта бошад дар формати зерин "user@example.com"',
        urlText: 'Ин майдон бояд формати URL дошта бошад "http:/' + '/www.example.com"',
        alphaText: 'Ин майдон бояд танҳо ҳарфҳои лотинӣ ва лақаби зерро дар бар гирад "_"',
        alphanumText: 'Ин майдон бояд танҳо ҳарфҳои лотинӣ, рақамҳо ва лақаби зерро дар бар гирад "_"'
      })
    }

    if (Ext.form.field.HtmlEditor) {
      Ext.apply(Ext.form.field.HtmlEditor.prototype, {
        createLinkText: 'Суроғаро ворид кунед:',
        buttonTips: {
          bold: {
            title: 'Нимғафс (Ctrl+B)',
            text: 'Истифодаи шакли нимғафс дар матни ҷудокардашуда.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          italic: {
            title: 'Шакли моил (Ctrl+I)',
            text: 'Истифодаи шакли моил дар матни ҷудокардашуда.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          underline: {
            title: 'Ба зераш хаткашидашуда (Ctrl+U)',
            text: 'Ба зери матни ҷудокардашуда хат кашидан.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          increasefontsize: {
            title: 'Калон кардани андозаи чопӣ',
            text: 'Калон кардани андозаи ҳарфи чопӣ.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          decreasefontsize: {
            title: 'Хурд кардани ҳарфи чопӣ',
            text: 'Хурд кардани ҳарфи чопӣ.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          backcolor: {
            title: 'Анбоштан',
            text: 'Тағйир додани ранги замина барои матн ё сарсатри ҷудокардашуда.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          forecolor: {
            title: 'Ранги матн',
            text: 'Тағйир додани ранги матн.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          justifyleft: {
            title: 'Баробар кардани матн аз канори чап',
            text: 'Баробар кардани матн аз канори чап.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          justifycenter: {
            title: 'Дар байн',
            text: 'Мутобиқ кардани матн дар байн.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          justifyright: {
            title: 'Баробар кардани матн аз канори рост',
            text: 'Баробар кардани матн аз канори чап рост.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          insertunorderedlist: {
            title: 'Нишонгарҳо',
            text: 'НРӯйхати нишонгузоришуда оғоз гардад.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          insertorderedlist: {
            title: 'Рақамгузорӣ',
            text: 'Рӯйхати рақамгузоришуда оғоз гардад.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          createlink: {
            title: 'Гиперистинод гузошта шавад',
            text: 'Сохтани истинод, аз ҷудокардашуда матн.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          },
          sourceedit: {
            title: 'Рамзи аввалия',
            text: 'Ба рамзи аввалия гузашта шавад.',
            cls: Ext.baseCSSPrefix + 'html-editor-tip'
          }
        }
      })
    }

    if (Ext.grid.header.Container) {
      Ext.apply(Ext.grid.header.Container.prototype, {
        sortAscText: 'Аз рӯи афзоиш дараҷабандӣ шавад',
        sortDescText: 'Аз рӯи коҳиш дараҷабандӣ шавад',
        lockText: 'Сутун маҳкам карда шавад',
        unlockText: 'Маҳкам кардани сутун бардошта шавад',
        columnsText: 'Сутунҳо'
      })
    }

    if (Ext.grid.feature.Grouping) {
      Ext.apply(Ext.grid.feature.Grouping.prototype, {
        emptyGroupText: '(Холӣ)',
        groupByText: 'Аз рӯи ин соҳа гурӯҳбандӣ кунед',
        showGroupsText: 'Намоиш аз ҷониби гурӯҳ'
      })
    }

    if (Ext.grid.PropertyColumnModel) {
      Ext.apply(Ext.grid.PropertyColumnModel.prototype, {
        nameText: 'Номгуй',
        valueText: 'Арзиш',
        dateFormat: 'd.m.Y'
      })
    }

    if (Ext.SplitLayoutRegion) {
      Ext.apply(Ext.SplitLayoutRegion.prototype, {
        splitTip: 'Барои тағйир додани андоза бикашед.',
        collapsibleSplitTip: 'Барои тағйир додани андоза бикашед. Ҳуппоки дукарата панелро пинҳон мекунад.'
      })
    }

    if (Ext.layout.BorderLayout && Ext.layout.BorderLayout.SplitRegion) {
      Ext.apply(Ext.layout.BorderLayout.SplitRegion.prototype, {
        splitTip: 'Барои тағйир додани андоза бикашед.',
        collapsibleSplitTip: 'Барои тағйир додани андоза бикашед. Ҳуппоки дукарата панелро пинҳон мекунад.'
      })
    }

    if (Ext.form.CheckboxGroup) {
      Ext.apply(Ext.form.CheckboxGroup.prototype, {
        blankText: 'Шумо бояд ҳадди аққал як мавқеъро дар гурӯҳ интихоб кунед'
      })
    }

    if (Ext.tab.Tab) {
      Ext.apply(Ext.tab.Tab.prototype, {
        closeText: 'Варақаи иловагӣ баста шавад'
      })
    }

    if (Ext.form.Basic) {
      Ext.form.Basic.prototype.waitTitle = 'Лутфан, мунтазир шавед...'
    }
  })
}
