$context:
  type: settings

uba.user.publicRegistrationSubject:
  name: Subject of email, sent to new user on public registration
  description: Subject of email, sent to new user on public registration
  type: string
uba.user.publicRegistrationReportCode:
  name: Report code for generating email, sent to new user on public registration
  description: Report code for generating email, sent to new user on public registration
  type: string